We attach the evidences here:

/home/ubuntu/Desktop/break/break/2015/157.js/code/build/logappend:230
	return new Promise( function( fulfill, reject ) {
	           ^
ReferenceError: Promise is not defined
    at handleBatch (/home/ubuntu/Desktop/break/break/2015/157.js/code/build/logappend:230:13)
    at Object.<anonymous> (/home/ubuntu/Desktop/break/break/2015/157.js/code/build/logappend:352:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

